import { initDb, getDb } from './schema.js';

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function seed() {
  initDb();
  const db = getDb();

  // --- Categories ---
  const insertCat = db.prepare(
    'INSERT OR IGNORE INTO categories (name, slug, description, icon, sort_order) VALUES (?, ?, ?, ?, ?)'
  );

  const categories = [
    ['DNA Skincare & Beauty', 'dna-skincare-beauty', 'Personalized skincare, haircare, and anti-aging products matched to your genetic profile', 'face', 1],
    ['Nutrigenomics', 'nutrigenomics', 'DNA-based diet plans, nutrition optimization, and food-gene interactions', 'nutrition', 2],
    ['Biological Age & Longevity', 'biological-age-longevity', 'Epigenetic clocks, biological age testing, and longevity science', 'clock', 3],
    ['At-Home DNA Kits', 'at-home-dna-kits', 'Consumer genetic testing kits for health, wellness, and trait insights', 'dna', 4],
    ['DNA-Based Supplements', 'dna-supplements', 'Custom vitamin and supplement stacks personalized to your genetics', 'supplements', 5],
    ['Practitioners & Platforms', 'practitioners-platforms', 'Genetic counselors, telehealth platforms, and functional medicine practitioners', 'practitioners', 6],
  ];

  const catMap = {};
  for (const c of categories) {
    insertCat.run(...c);
    catMap[c[0]] = db.prepare('SELECT id FROM categories WHERE slug = ?').get(c[1]).id;
  }

  // --- Companies ---
  const insertCompany = db.prepare(`
    INSERT OR IGNORE INTO companies (name, slug, category_id, description, website, logo_initials, logo_gradient, org_label, rating, tags, featured, badge, country)
    VALUES (@name, @slug, @category_id, @description, @website, @logo_initials, @logo_gradient, @org_label, @rating, @tags, @featured, @badge, @country)
  `);

  const companies = [
    // === DNA Skincare & Beauty ===
    { name: 'Allel', cat: 'DNA Skincare & Beauty', desc: 'Swedish luxury DNA-matched skincare subscription. Analyzes 16 genetic markers across five drivers of aging — intrinsic aging, glycation, photoaging, oxidative stress, and inflammation — then formulates personalized serums and moisturizers.', web: 'https://allel.com', initials: 'AL', grad: 'linear-gradient(135deg, #667eea, #764ba2)', org: 'DNA Skincare · Sweden', rating: 4.8, tags: '["DNA Skincare","Subscription","Anti-Aging"]', featured: 1, badge: 'featured', country: 'Sweden' },
    { name: 'SkinGenie', cat: 'DNA Skincare & Beauty', desc: 'AI-powered platform using a proprietary algorithm to explore predispositions to 30+ skin traits, then maps consumers to products best suited to their genetic skincare needs. Backed by J&J Innovation.', web: 'https://www.skingenie.com', initials: 'SG', grad: 'linear-gradient(135deg, #f093fb, #f5576c)', org: 'DNA Skincare · J&J Backed', rating: 4.5, tags: '["AI","Skin Traits","J&J"]', featured: 0, badge: null, country: 'USA' },
    { name: 'EpigenCare', cat: 'DNA Skincare & Beauty', desc: 'Offers SKINTELLI epigenetic skin test that evaluates skin quality through epigenetic markers (not just DNA sequence) for personalized skincare recommendations. Backed by J&J Innovation.', web: 'https://www.epigencare.com', initials: 'EC', grad: 'linear-gradient(135deg, #fd79a8, #e84393)', org: 'Epigenetic Skincare', rating: 4.4, tags: '["Epigenetics","Skin Test","J&J Backed"]', featured: 0, badge: null, country: 'USA' },
    { name: 'SkinDNA', cat: 'DNA Skincare & Beauty', desc: 'Tests 16 core genetic SNPs related to skin protection and premature aging. Built one of the world\'s largest dermagenetics databases with over 2 million DNA profiles.', web: 'https://www.skindna.com.au', initials: 'SD', grad: 'linear-gradient(135deg, #a29bfe, #6c5ce7)', org: 'Dermagenetics · Australia', rating: 4.3, tags: '["SNP Testing","Database","Anti-Aging"]', featured: 0, badge: null, country: 'Australia' },
    { name: 'SKINSHIFT', cat: 'DNA Skincare & Beauty', desc: 'Founded by Dr. Ruthie Harper. Uses DNA analysis to identify skin genetic strengths and weaknesses, then provides personalized skincare and anti-aging strategy with matched products and supplements.', web: 'https://skinshift.com', initials: 'SS', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'DNA Skincare · Dr. Harper', rating: 4.5, tags: '["Physician-Led","Supplements","Anti-Aging"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Caligenix', cat: 'DNA Skincare & Beauty', desc: 'Precision health biotech with Dermatype (skincare) and Biotyp (wellness) brands using AI algorithms and genomic technologies. Includes skin DNA test, facial AI analysis, and product matching.', web: 'https://caligenix.com', initials: 'CX', grad: 'linear-gradient(135deg, #00cec9, #0984e3)', org: 'Precision Biotech', rating: 4.2, tags: '["AI","Facial Analysis","Genomics"]', featured: 0, badge: null, country: 'USA' },
    { name: 'TrichoTest', cat: 'DNA Skincare & Beauty', desc: 'Genetic test for personalized hair loss treatment by Fagron Genomics. Analyzes 13 genes and 48 genetic variations related to alopecia to recommend targeted hair restoration therapies.', web: 'https://gxsciences.com/trichotest', initials: 'TT', grad: 'linear-gradient(135deg, #fdcb6e, #e17055)', org: 'Hair Genetics · Fagron', rating: 4.6, tags: '["Hair Loss","Genetics","Practitioner"]', featured: 0, badge: 'popular', country: 'USA' },
    { name: '24Genetics', cat: 'DNA Skincare & Beauty', desc: 'Spanish company offering skin and hair DNA test analyzing 700,000+ DNA markers. Provides predispositions related to anti-aging, moisturization, elasticity, and pigmentation.', web: 'https://24genetics.com', initials: '24', grad: 'linear-gradient(135deg, #fab1a0, #e17055)', org: 'DNA Testing · Spain', rating: 4.3, tags: '["Skin","Hair","700K Markers"]', featured: 0, badge: null, country: 'Spain' },

    // === Nutrigenomics ===
    { name: 'GenoPalate', cat: 'Nutrigenomics', desc: 'Analyzes genetic variants related to nutrient digestion and designs personalized meal plans and food recommendations. Also offers DNA-based personalized vitamins tailored to your metabolism.', web: 'https://www.genopalate.com', initials: 'GP', grad: 'linear-gradient(135deg, #43e97b, #38f9d7)', org: 'Nutrigenomics', rating: 4.5, tags: '["DNA Nutrition","Meal Plans","Vitamins"]', featured: 1, badge: 'featured', country: 'USA' },
    { name: 'DNAfit', cat: 'Nutrigenomics', desc: 'Offers nutrigenomics DNA tests with fitness, sleep, drug response, and cancer marker analysis. Personalized nutrition and exercise recommendations. Now part of Prenetics (CircleDNA parent).', web: 'https://www.dnafit.com', initials: 'DF', grad: 'linear-gradient(135deg, #0984e3, #74b9ff)', org: 'Prenetics / CircleDNA', rating: 4.4, tags: '["Fitness","Nutrition","Sleep"]', featured: 0, badge: null, country: 'UK' },
    { name: 'Nutrigenomix', cat: 'Nutrigenomics', desc: 'World\'s first clinical genetic test for personalized nutrition (launched 2014). Analyzes 50+ key genes. Validated by randomized controlled trials. Available through authorized healthcare providers.', web: 'https://nutrigenomix.com', initials: 'NX', grad: 'linear-gradient(135deg, #00b894, #00cec9)', org: 'Clinical Nutrigenomics', rating: 4.7, tags: '["Clinical","RCT Validated","50+ Genes"]', featured: 1, badge: 'featured', country: 'Canada' },
    { name: 'DnaNudge', cat: 'Nutrigenomics', desc: 'Wearable wristband loaded with your DNA profile. Scan grocery barcodes while shopping for instant thumbs-up/thumbs-down on food compatibility with your genetics. Imperial College London spin-out.', web: 'https://www.dnanudge.com', initials: 'DN', grad: 'linear-gradient(135deg, #fdcb6e, #e17055)', org: 'Nutrigenomics · Imperial College', rating: 4.3, tags: '["Wearable","Grocery Scanner","Real-Time"]', featured: 0, badge: 'new', country: 'UK' },
    { name: 'Nutrition Genome', cat: 'Nutrigenomics', desc: 'Provides 170+ health reports covering vitamin requirements, macronutrient metabolism, toxin sensitivity, DNA repair, hormones, sleep optimization, and mental health from a single DNA test.', web: 'https://nutritiongenome.com', initials: 'NG', grad: 'linear-gradient(135deg, #a29bfe, #6c5ce7)', org: 'Nutrigenomics', rating: 4.5, tags: '["170+ Reports","Vitamins","Metabolism"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Gene Food', cat: 'Nutrigenomics', desc: 'Accepts uploaded raw DNA data from 23andMe, Ancestry, etc. Provides personalized diet type assignment, health reports, and food sensitivity analysis using nutrigenomic principles.', web: 'https://www.mygenefood.com', initials: 'GF', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'DNA Diet Analysis', rating: 4.2, tags: '["Raw Data","Diet Type","Food Sensitivity"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Xcode Life', cat: 'Nutrigenomics', desc: 'Offers the largest portfolio of genetic trait reports including Gene Nutrition, Gene Fitness, Gene Skin, MTHFR/Methylation, and Gene Sleep. Accepts DNA data from all major testing companies.', web: 'https://www.xcode.life', initials: 'XL', grad: 'linear-gradient(135deg, #fab1a0, #e17055)', org: 'Multi-Trait Genomics', rating: 4.1, tags: '["Multi-Trait","MTHFR","Compatible"]', featured: 0, badge: null, country: 'India' },
    { name: 'Genate', cat: 'Nutrigenomics', desc: 'First prenatal genetics test identifying which key nutrients your body doesn\'t metabolize efficiently. DNA-based prenatal nutrition recommendations with genetic counseling.', web: 'https://genate.com', initials: 'GN', grad: 'linear-gradient(135deg, #fd79a8, #e84393)', org: 'Prenatal Nutrigenomics', rating: 4.6, tags: '["Prenatal","Folate","Counseling"]', featured: 0, badge: 'new', country: 'USA' },

    // === Biological Age & Longevity ===
    { name: 'TruDiagnostic', cat: 'Biological Age & Longevity', desc: 'Measures 1M+ DNA methylation locations via the TruAge test, developed with Harvard, Yale, and Duke. 30+ page reports on biological aging factors. Gold standard in epigenetic age testing.', web: 'https://www.trudiagnostic.com', initials: 'TD', grad: 'linear-gradient(135deg, #00cec9, #0984e3)', org: 'Biological Age Testing', rating: 4.9, tags: '["Epigenetic Clock","Biological Age","Harvard"]', featured: 1, badge: 'featured', country: 'USA' },
    { name: 'Tally Health', cat: 'Biological Age & Longevity', desc: 'Co-founded by Harvard longevity researcher David Sinclair. Proprietary TallyAge epigenetic clock analyzes ~850,000 DNA methylation sites. Personalized diet, fitness, sleep, and mental health recommendations.', web: 'https://tallyhealth.com', initials: 'TH', grad: 'linear-gradient(135deg, #a29bfe, #6c5ce7)', org: 'Longevity · David Sinclair', rating: 4.8, tags: '["Epigenetic Age","Longevity","Harvard"]', featured: 1, badge: 'new', country: 'USA' },
    { name: 'InsideTracker', cat: 'Biological Age & Longevity', desc: 'Founded by MIT and Tufts scientists. Combines 40+ blood biomarkers with DNA analysis of 20,000 genetic markers. InnerAge biological age score. 80% of users improve at-risk biomarkers.', web: 'https://www.insidetracker.com', initials: 'IT', grad: 'linear-gradient(135deg, #0984e3, #74b9ff)', org: 'Blood + DNA Testing', rating: 4.7, tags: '["Blood Biomarkers","DNA","InnerAge"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Elysium Health', cat: 'Biological Age & Longevity', desc: 'The Elysium Index measures 10 areas of aging via epigenetic testing, providing biological age, cumulative rate of aging, and system scores for nine body systems.', web: 'https://www.elysiumhealth.com', initials: 'EH', grad: 'linear-gradient(135deg, #636e72, #2d3436)', org: 'Epigenetic Age Testing', rating: 4.5, tags: '["Epigenetic Index","9 Systems","NAD+"]', featured: 0, badge: null, country: 'USA' },
    { name: 'GlycanAge', cat: 'Biological Age & Longevity', desc: 'Uses glycan biomarkers (not DNA methylation) to evaluate inflammatory aging. Simple finger-prick home test cited in 200+ scientific publications.', web: 'https://glycanage.com', initials: 'GA', grad: 'linear-gradient(135deg, #e17055, #d63031)', org: 'Glycan Biomarkers', rating: 4.4, tags: '["Glycans","Inflammation","200+ Papers"]', featured: 0, badge: null, country: 'Croatia' },
    { name: 'NOVOS', cat: 'Biological Age & Longevity', desc: 'Public benefit longevity biotech. NOVOS Age test combines DunedinPACE (Columbia/Duke), Harvard-collaborated biological age clock, and telomere length. Also sells longevity supplements targeting all 12 hallmarks of aging.', web: 'https://novoslabs.com', initials: 'NV', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'Longevity Biotech', rating: 4.6, tags: '["12 Hallmarks","DunedinPACE","Supplements"]', featured: 0, badge: 'popular', country: 'USA' },
    { name: 'myDNAge', cat: 'Biological Age & Longevity', desc: 'Biological age test based on Dr. Steve Horvath\'s original epigenetic clock — the most cited epigenetic age clock in research. Single biological age number from DNA methylation analysis.', web: 'https://www.mydnage.com', initials: 'MD', grad: 'linear-gradient(135deg, #fab1a0, #e17055)', org: 'Horvath Clock', rating: 4.3, tags: '["Horvath Clock","Original","Methylation"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Muhdo', cat: 'Biological Age & Longevity', desc: 'UK company offering DNA + epigenetic testing. Analyzes 1,000 SNPs for 300+ reports. Calculates eight different age clocks including skin, eyes, memory, hearing, plus inflammatory scores.', web: 'https://muhdo.com', initials: 'MH', grad: 'linear-gradient(135deg, #74b9ff, #0984e3)', org: 'Multi-Clock Epigenetics · UK', rating: 4.2, tags: '["8 Age Clocks","Skin Age","Epigenetics"]', featured: 0, badge: null, country: 'UK' },

    // === At-Home DNA Kits ===
    { name: 'Nebula Genomics', cat: 'At-Home DNA Kits', desc: 'Full whole genome sequencing (all 6.4 billion base pairs) with 30x coverage. Comprehensive health, ancestry, and trait reports. Subscription model unlocks new insights as research advances.', web: 'https://nebula.org', initials: 'NB', grad: 'linear-gradient(135deg, #0984e3, #6c5ce7)', org: 'Whole Genome Sequencing', rating: 4.7, tags: '["WGS","Health Reports","Privacy-First"]', featured: 1, badge: 'featured', country: 'USA' },
    { name: 'CircleDNA', cat: 'At-Home DNA Kits', desc: '500+ reports across nutrition, fitness, skin, mental health, cancer risk, and common health conditions. One of the most comprehensive consumer DNA kits available.', web: 'https://circledna.com', initials: 'CD', grad: 'linear-gradient(135deg, #00cec9, #00b894)', org: '500+ Reports', rating: 4.5, tags: '["500+ Reports","Cancer Risk","Skin"]', featured: 0, badge: null, country: 'Hong Kong' },
    { name: 'SelfDecode', cat: 'At-Home DNA Kits', desc: 'Provides 1,500+ health reports. Accepts uploaded raw DNA data from AncestryDNA, FamilyTreeDNA, and others. AI-powered health recommendations.', web: 'https://selfdecode.com', initials: 'SD', grad: 'linear-gradient(135deg, #fdcb6e, #f39c12)', org: 'AI Health Reports', rating: 4.4, tags: '["1500+ Reports","Raw Data","AI"]', featured: 0, badge: null, country: 'USA' },
    { name: '23andMe', cat: 'At-Home DNA Kits', desc: 'The pioneer of consumer DNA testing. ~150 reports including health predispositions, carrier screens, wellness insights, and pharmacogenomic reports alongside ancestry.', web: 'https://www.23andme.com', initials: '23', grad: 'linear-gradient(135deg, #a29bfe, #6c5ce7)', org: 'Consumer DNA Pioneer', rating: 4.2, tags: '["Pioneer","Health","Ancestry"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Color Health', cat: 'At-Home DNA Kits', desc: 'Clinical-grade genetic tests covering 60+ genes for cancer (including BRCA1/BRCA2), heart disease, and medication response. Physician-ordered testing.', web: 'https://www.color.com', initials: 'CH', grad: 'linear-gradient(135deg, #e17055, #d63031)', org: 'Clinical-Grade', rating: 4.6, tags: '["Clinical","BRCA","Cancer Risk"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Sequencing.com', cat: 'At-Home DNA Kits', desc: 'DNA app marketplace that accepts data from any genetic test. Offers a marketplace of health apps including nutrition, skincare, fitness, and personalized vitamin reports.', web: 'https://sequencing.com', initials: 'SQ', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'DNA App Marketplace', rating: 4.1, tags: '["App Store","Any Test","Marketplace"]', featured: 0, badge: null, country: 'USA' },

    // === DNA-Based Supplements ===
    { name: 'Rootine', cat: 'DNA-Based Supplements', desc: 'Tests 52 scientifically validated genes, combines DNA + blood nutrient levels + lifestyle data to create custom vitamin packs. Proprietary slow-release microbead delivery for 10+ hours of absorption.', web: 'https://rootine.co', initials: 'RT', grad: 'linear-gradient(135deg, #f093fb, #f5576c)', org: 'DNA Supplements', rating: 4.7, tags: '["Custom Vitamins","DNA + Blood","Subscription"]', featured: 1, badge: 'popular', country: 'USA' },
    { name: 'Nourished', cat: 'DNA-Based Supplements', desc: 'Uses patented 3D printing technology to create personalized 7-layer nutrient gummy stacks. 19 patents on Birmingham-developed technology. Products made and delivered within 3 days.', web: 'https://get-nourished.com', initials: 'NR', grad: 'linear-gradient(135deg, #fdcb6e, #e17055)', org: '3D-Printed Vitamins · UK', rating: 4.5, tags: '["3D Printed","7-Layer","Personalized"]', featured: 0, badge: 'new', country: 'UK' },
    { name: 'NOVOS Supplements', cat: 'DNA-Based Supplements', desc: 'DNA biological age testing paired with longevity supplements targeting all 12 hallmarks of aging. 73% of users showed reduced biological aging pace in clinical study.', web: 'https://novoslabs.com', initials: 'NV', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'Longevity Supplements', rating: 4.6, tags: '["12 Hallmarks","Clinical Data","Longevity"]', featured: 0, badge: null, country: 'USA' },
    { name: '10X Health System', cat: 'DNA-Based Supplements', desc: 'Founded by Gary Brecka. Gene testing alongside IV therapy and precision wellness services. DNA results inform personalized supplement protocols for peak performance.', web: 'https://10xhealthsystem.com', initials: '10', grad: 'linear-gradient(135deg, #636e72, #2d3436)', org: 'Gary Brecka · Performance', rating: 4.3, tags: '["Performance","IV Therapy","Gene Testing"]', featured: 0, badge: null, country: 'USA' },
    { name: 'Vitl', cat: 'DNA-Based Supplements', desc: 'UK-based personalized vitamin, DNA, and blood testing company. Combines health questionnaire with optional DNA and blood test results to personalize supplement formulas.', web: 'https://vitl.com', initials: 'VT', grad: 'linear-gradient(135deg, #74b9ff, #0984e3)', org: 'DNA Vitamins · UK', rating: 4.2, tags: '["Blood + DNA","Questionnaire","UK"]', featured: 0, badge: null, country: 'UK' },

    // === Practitioners & Platforms ===
    { name: 'Genome Medical', cat: 'Practitioners & Platforms', desc: 'Telehealth genetic counseling with 35+ clinicians available in all 50 US states. Genetic counselors, medical geneticists, and primary care physicians. Appointments within a week.', web: 'https://www.genomemedical.com', initials: 'GM', grad: 'linear-gradient(135deg, #55efc4, #00b894)', org: 'Genetic Counseling', rating: 4.8, tags: '["Telehealth","Counseling","All 50 States"]', featured: 1, badge: 'featured', country: 'USA' },
    { name: '3X4 Genetics', cat: 'Practitioners & Platforms', desc: 'Practitioner-only DNA testing platform analyzing 134+ genes across metabolism, inflammation, detoxification, fitness, hormones, and cognition. Results reviewed by certified practitioners.', web: 'https://3x4genetics.com', initials: '3X', grad: 'linear-gradient(135deg, #0984e3, #74b9ff)', org: 'Practitioner Platform', rating: 4.6, tags: '["134 Genes","Practitioner-Only","Functional Med"]', featured: 0, badge: null, country: 'USA' },
    { name: 'GeneSight', cat: 'Practitioners & Platforms', desc: 'Pharmacogenomic test by Myriad Genetics analyzing genes relevant to psychotropic medications for depression, anxiety, ADHD. Helps clinicians reduce trial-and-error prescribing.', web: 'https://genesight.com', initials: 'GS', grad: 'linear-gradient(135deg, #a29bfe, #6c5ce7)', org: 'Myriad Genetics · Mental Health', rating: 4.5, tags: '["Pharmacogenomics","Mental Health","Myriad"]', featured: 0, badge: null, country: 'USA' },
    { name: 'StrateGene', cat: 'Practitioners & Platforms', desc: 'Created by Dr. Ben Lynch. Identifies 100+ genetic variations across 9 key health pathways. Designed for practitioners and health-conscious consumers. Works with 23andMe and Ancestry data.', web: 'https://www.seekinghealth.com/products/strategene-report', initials: 'SG', grad: 'linear-gradient(135deg, #00b894, #00cec9)', org: 'Dr. Ben Lynch', rating: 4.4, tags: '["100+ Variants","9 Pathways","MTHFR"]', featured: 0, badge: null, country: 'USA' },
    { name: 'InformedDNA', cat: 'Practitioners & Platforms', desc: 'Telegenetic counseling with counselors specializing in prenatal, oncology, neurology, cardiology, ophthalmology, mental health, and more. Real-time expert consultation from home.', web: 'https://informeddna.com', initials: 'ID', grad: 'linear-gradient(135deg, #fdcb6e, #f39c12)', org: 'Telegenetic Counseling', rating: 4.5, tags: '["Multi-Specialty","Telehealth","Prenatal"]', featured: 0, badge: null, country: 'USA' },
    { name: 'IntellxxDNA', cat: 'Practitioners & Platforms', desc: 'Practitioner platform examining SNPs across nutrient metabolism, detox, inflammation, cardiovascular, and neurological function. Trains practitioners through "Genomics University."', web: 'https://intellxxdna.com', initials: 'IX', grad: 'linear-gradient(135deg, #e17055, #d63031)', org: 'Genomics University', rating: 4.3, tags: '["Practitioner Training","SNPs","Functional Med"]', featured: 0, badge: null, country: 'USA' },
  ];

  const insertMany = db.transaction((items) => {
    for (const c of items) {
      insertCompany.run({
        name: c.name,
        slug: slugify(c.name),
        category_id: catMap[c.cat],
        description: c.desc,
        website: c.web,
        logo_initials: c.initials,
        logo_gradient: c.grad,
        org_label: c.org,
        rating: c.rating,
        tags: c.tags,
        featured: c.featured,
        badge: c.badge,
        country: c.country,
      });
    }
  });
  insertMany(companies);

  // --- Research Papers ---
  const insertPaper = db.prepare(`
    INSERT OR IGNORE INTO research_papers (title, slug, journal, pub_date, summary, consumer_relevance, tags, category, source_url, featured)
    VALUES (@title, @slug, @journal, @pub_date, @summary, @consumer_relevance, @tags, @category, @source_url, @featured)
  `);

  const papers = [
    { title: 'VYJUVEK: First FDA-Approved Topical Gene Therapy', journal: 'Nature', pub_date: '2023-05', summary: 'FDA approved the world\'s first redosable topical gene therapy for dystrophic epidermolysis bullosa. Uses engineered HSV-1 virus to deliver functional COL7A1 genes directly into wounded skin. 65% wound closure vs 26% placebo in clinical trials.', consumer_relevance: 'Proves gene therapy can be painted onto skin and safely re-applied. The same delivery platform could carry genes for collagen production or anti-aging factors into consumer skin treatments.', tags: '["Gene Therapy","Collagen","FDA Approved","Topical"]', category: 'skin', source_url: 'https://www.nature.com/articles/d41573-023-00095-9', featured: 1 },
    { title: 'Skin Cell Aging Reversed by 10+ Years via mRNA', journal: 'ESDR Conference', pub_date: '2024-09', summary: 'Turn Biotechnologies demonstrated mRNA-based epigenetic reprogramming that reversed aging in human dermal fibroblasts by up to 10.4 years. First-ever rejuvenation of human keratinocytes (90% of the epidermis).', consumer_relevance: 'Closest any company has come to a true age-reversal skincare product at the cellular level. Resets cells to younger epigenetic state, restoring natural collagen and elastin production. Clinical trials planned for 2026.', tags: '["Epigenetic Reversal","mRNA","Anti-Aging","Clinical Trial"]', category: 'skin', source_url: 'https://www.prnewswire.com/news-releases/turn-biotechnologies-reports-historic-skin-cell-rejuvenation-breakthroughs-at-esdr-this-week-302238018.html', featured: 1 },
    { title: 'Gray Hair Is Caused by Stuck Stem Cells, Not Cell Death', journal: 'Nature', pub_date: '2023-04', summary: 'Landmark study showed melanocyte stem cells get stuck in a differentiated state within hair follicle niches, losing their ability to cycle. The stuck McSC mechanism is the primary cause of hair graying, not cell death.', consumer_relevance: 'Fundamentally changed our understanding of gray hair. Opens the door to treatments that could restore hair color by reactivating stuck melanocyte stem cells.', tags: '["Hair Science","Melanocytes","Reversible","Stem Cells"]', category: 'beauty', source_url: 'https://www.nature.com/articles/s41586-023-05960-6', featured: 1 },
    { title: 'First Telomere-Lengthening Gene Therapy in Humans', journal: 'NEJM Evidence', pub_date: '2025', summary: 'EXG-34217 uses AAV to deliver the ZSCAN4 gene into patient stem cells. In two individuals, treatment successfully lengthened telomeres and improved immune cell counts over 24 months without major adverse effects.', consumer_relevance: 'First clinical proof that gene therapy can reverse telomere aging in humans. The path from rare disease to elective longevity therapy follows VYJUVEK\'s trajectory.', tags: '["Telomeres","Gene Therapy","Longevity","First-in-Human"]', category: 'longevity', source_url: 'https://scienceblog.cincinnatichildrens.org/first-gene-therapy-trial-for-telomere-biology-disorders-shows-promising-results/', featured: 1 },
    { title: 'GLP1R Gene Variant Predicts Semaglutide Weight Loss Response', journal: 'Obesity (Wiley)', pub_date: '2025', summary: 'GLP1R variant rs6923761 predicts weight loss on semaglutide 2.4mg. AA genotype lost weight at 1.64%/month vs 1.04% for G-carriers. Women with AA genotype lost weight more than twice as fast as men with G allele.', consumer_relevance: 'Pharmacogenomic testing could predict who responds well to Ozempic/Wegovy before starting, saving months of trial-and-error and thousands of dollars.', tags: '["Pharmacogenomics","GLP-1","Weight Loss","Ozempic"]', category: 'nutrition', source_url: 'https://onlinelibrary.wiley.com/doi/10.1002/oby.24300', featured: 1 },
    { title: 'Epigenetic Diet Reverses Biological Age by 2+ Years', journal: 'Aging', pub_date: '2025', summary: 'Specific dietary patterns rich in green tea, turmeric, rosemary, garlic, and berries were associated with a 2.04-year reduction in epigenetic age through DNA methylation pathway modulation.', consumer_relevance: 'Consumers can literally eat their way to younger DNA methylation patterns. Validates functional foods and supplements like EGCG, curcumin, and resveratrol as evidence-based epigenetic anti-aging.', tags: '["Epigenetic Diet","Methylation","Nutrition","Anti-Aging"]', category: 'nutrition', source_url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12074822/', featured: 1 },
    { title: 'CRISPR Converts White Fat to Calorie-Burning Brown Fat', journal: 'Nature Communications', pub_date: '2024', summary: 'CRISPR-engineered human fat cells (HUMBLE) convert white adipose tissue into metabolically active brown fat. Mice gained significantly less weight with 35% improved glucose tolerance and insulin sensitivity.', consumer_relevance: 'A potential one-time obesity intervention: gene-edited fat that burns calories instead of storing them. A pill version targeting the same pathway is under development.', tags: '["CRISPR","Metabolism","Obesity","Brown Fat"]', category: 'nutrition', source_url: 'https://crisprmedicinenews.com/news/crispr-gene-therapy-makes-fat-cells-burn-fat-and-prevents-obesity-in-mice/', featured: 0 },
    { title: 'TAC: A Pill That Reactivates the Body\'s Telomerase Gene', journal: 'MD Anderson', pub_date: '2025', summary: 'TAC (TERT Activating Compound) epigenetically de-represses the TERT gene and restores physiological telomerase expression. In preclinical models equivalent to adults over 75, 6 months of treatment led to new neuron formation.', consumer_relevance: 'Unlike gene therapy, TAC is a pill-form compound that activates the body\'s own telomerase gene. Could be the first supplement-like telomerase activator with rigorous mechanistic evidence.', tags: '["Small Molecule","Telomerase","Oral","Aging"]', category: 'longevity', source_url: 'https://www.mdanderson.org/newsroom/activating-molecular-target-reverses-multiple-hallmarks-of-aging.h00-159698334.html', featured: 1 },
    { title: 'mRNA Restores Elastin Production in Human Skin', journal: 'Molecular Therapy (Cell Press)', pub_date: '2024', summary: 'Synthetic modified mRNA encoding tropoelastin triggered de novo elastin synthesis in human skin cells — the first demonstration of mRNA-mediated elastin production in fibroblasts and intact skin tissue.', consumer_relevance: 'Elastin loss is irreversible in adults. mRNA therapy could restore production, addressing a fundamental cause of skin sagging that no current cosmetic product can fix.', tags: '["mRNA","Elastin","Skin Science","Collagen"]', category: 'skin', source_url: 'https://www.cell.com/molecular-therapy-family/nucleic-acids/fulltext/S2162-2531(18)30044-1', featured: 0 },
    { title: 'OSK Partial Reprogramming Extends Lifespan 109% in Aged Mice', journal: 'Cellular Reprogramming', pub_date: '2024-02', summary: 'AAV-delivered inducible OSK (Yamanaka factors without c-Myc) in 124-week-old mice extended median remaining lifespan by 109%. Human keratinocytes from a 65-year-old showed significant epigenetic age reversal.', consumer_relevance: 'Among the strongest evidence that partial reprogramming can reverse skin aging without cancer risk. Old skin cells produced collagen like cells 30 years younger.', tags: '["Yamanaka Factors","Reprogramming","Lifespan","Collagen"]', category: 'longevity', source_url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10909732/', featured: 0 },
    { title: 'CRISPR Targeting Hair Loss: SRD5A2, FGF5, and Wnt Pathways', journal: 'Cells (MDPI)', pub_date: '2025', summary: 'CRISPR/Cas9 applied to key hair loss targets: SRD5A2 (converts testosterone to DHT), FGF5 (hair growth inhibitor), and VDR. The Wnt/beta-catenin pathway confirmed as master switch for follicle growth.', consumer_relevance: 'Rather than daily finasteride with side effects, a one-time CRISPR edit to SRD5A2 could permanently reduce DHT-driven hair loss. Editing FGF5 could extend hair growth phase.', tags: '["CRISPR","Hair Loss","DHT","Wnt Pathway"]', category: 'beauty', source_url: 'https://biomedres.us/pdfs/BJSTR.MS.ID.008587.pdf', featured: 0 },
    { title: 'Topical Lipid Nanoparticle CRISPR: Gene Editing in a Cream', journal: 'CRISPR Medicine News', pub_date: '2024', summary: 'Lipid nanoparticle-based CRISPR base editors formulated as a topical treatment applied directly to human skin tissue, correcting disease-causing mutations in situ without viral vectors.', consumer_relevance: 'The concept of gene editing in a cream is moving from science fiction to early-stage reality. Topical nanoparticle delivery could make gene therapies as simple as applying a lotion.', tags: '["Topical CRISPR","Nanoparticles","Base Editing","Skin"]', category: 'skin', source_url: 'https://crisprmedicinenews.com/news/painting-crispr-onto-the-skin-curing-a-rare-genetic-skin-diseases-with-topical-base-editing/', featured: 0 },
    { title: 'Dasatinib + Quercetin Senolytics Reduce Skin Senescent Cells', journal: 'Aging', pub_date: '2025', summary: 'Phase I pilot study: 19 participants receiving dasatinib + quercetin for 6 months showed significant changes in epigenetic age. Skin senescent cells and circulating SASP inflammatory factors were reduced.', consumer_relevance: 'Quercetin is a widely available supplement. This validates that a natural flavonoid can measurably clear senescent cells in human skin, driving consumer interest in senolytics.', tags: '["Senolytics","Quercetin","Skin Aging","Clinical Trial"]', category: 'longevity', source_url: 'https://www.aging-us.com/article/205581/text', featured: 0 },
    { title: 'AI + Multi-Omics Pharmacogenomics for Treatment Prediction', journal: 'ScienceDirect', pub_date: '2025', summary: 'Deep neural networks integrated with multi-omics data predict individual treatment responses. AI detects hidden gene-gene and gene-environment interaction patterns that traditional statistics miss.', consumer_relevance: 'AI could soon predict how your body responds to a specific supplement or skincare ingredient before you try it, based on your complete molecular profile.', tags: '["AI","Multi-Omics","Pharmacogenomics","Prediction"]', category: 'precision-wellness', source_url: 'https://www.sciencedirect.com/science/article/pii/S2949761225000537', featured: 0 },
    { title: 'Longevity Cosmeceuticals Defined as New Product Category', journal: 'Frontiers in Aging', pub_date: '2025', summary: 'Comprehensive review defined longevity cosmeceuticals as products incorporating ingredients with demonstrated effects on hallmarks of aging rather than simply moisturizing or masking aging signs.', consumer_relevance: 'Formalizes the market for science-backed anti-aging cosmetics that target cellular aging mechanisms. Consumers can evaluate products based on which aging hallmarks they address.', tags: '["Cosmeceuticals","Hallmarks of Aging","Anti-Aging","Market"]', category: 'beauty', source_url: 'https://www.frontiersin.org/journals/aging/articles/10.3389/fragi.2025.1586999/pdf', featured: 0 },
  ];

  const insertPapers = db.transaction((items) => {
    for (const p of items) {
      insertPaper.run({
        title: p.title,
        slug: slugify(p.title),
        journal: p.journal,
        pub_date: p.pub_date,
        summary: p.summary,
        consumer_relevance: p.consumer_relevance,
        tags: p.tags,
        category: p.category,
        source_url: p.source_url,
        featured: p.featured,
      });
    }
  });
  insertPapers(papers);

  const companyCount = db.prepare('SELECT COUNT(*) as n FROM companies').get().n;
  const paperCount = db.prepare('SELECT COUNT(*) as n FROM research_papers').get().n;
  const catCount = db.prepare('SELECT COUNT(*) as n FROM categories').get().n;

  console.log(`Seeded: ${companyCount} companies, ${paperCount} papers, ${catCount} categories`);
  db.close();
}

seed();
